const Map<int, String> storeNames = {
  1: 'Steam',
  2: 'Microsoft Store',
  3: 'PlayStation Store',
  4: 'App Store',
  5: 'GOG',
  6: 'Nintendo Store',
  7: 'Xbox 360 Store',
  8: 'Xbox One Store',
  9: 'Google Play',
  10: 'itch.io',
  11: 'Epic Games',
  12: 'Oculus',
  13: 'Stadia',
  14: 'Razer',
  15: 'Origin',
  16: 'Ubisoft Store',
  17: 'Amazon',
  18: 'PlayStation 3',
  19: 'PlayStation 4',
  20: 'Xbox Live Arcade',
  21: 'Wii U',
  22: 'Nintendo Switch',
  23: 'PS Vita',
  24: 'Nintendo 3DS',
  25: 'iOS',
  26: 'Android',
  27: 'Direct Download',
  28: 'Oculus Store',
  29: 'Samsung',
  30: 'Mac App Store',
  31: 'Windows Store',
  32: 'PlayStation 5',
  33: 'Xbox Series X|S',
  34: 'Other',
};